### ISSUE TITLE
System to get units back from Conquer attack

### ISSUE THREAD

**Issue by Galatex1** [Galatex1/inbrico#32]
Currently when player conquers a tile, only way for him to get his units back is to wait for 24 hours to pass to acttually claim the tile and then he can move his army back. There should be a way to recall his army back whenever, BUT that should make the tile not contested anymore as army needs to stay on contested tile for 24 hours to claim it.

**Comment by lizard29** [comment]
Also, army should stay on the tile after its claimed.

**Comment by Galatex1** [comment]
Players can now select contested tile and then one of their own tiles in range and send their units back as deffend command.
